# Generated by Django 3.0.8 on 2020-08-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='media/images/suzaku.jpg', upload_to='images/'),
        ),
    ]
