# Generated by Django 3.0.8 on 2020-08-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200821_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cover',
            new_name='image',
        ),
    ]
